[package]
name = "host"
version = "0.1.0"
edition = "2024"

[dependencies]
valida-rs = { git = "https://github.com/lita-xyz/valida-rs.git", branch = "no-deps" }
tempfile = "3.10.1"
valida-vm-api-linux-arm = "0.10.0"
