[package]
name = "guest"
version = "0.1.0"
edition = "2021"

[dependencies]
valida-rs = { git = "https://github.com/lita-xyz/valida-rs.git", branch = "main" }
k256 = { version = "0.13", features = ["ecdsa", "sha256"], default-features = false }
